# Generated by Django 5.2.17 on 2026-10-04 05:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('hospital', '0003_bed_status_since'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('LOW_SPO2', 'Low oxygen saturation'), ('HIGH_HEART_RATE', 'High heart rate'), ('LOW_BLOOD_PRESSURE', 'Low blood pressure'), ('HIGH_RESPIRATORY_RATE', 'High respiratory rate'), ('FEVER', 'Fever'), ('HIGH_OCCUPANCY', 'High bed occupancy'), ('EQUIPMENT_OVERHEATING', 'Equipment overheating'), ('EQUIPMENT_FAILURE', 'Equipment failure')], max_length=30)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=12)),
                ('subject', models.CharField(help_text='What the alert is about, e.g. "admission:12".', max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='hospital.admission')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='equipment.equipment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='hospital.unit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='alerts_aler_status_e70a14_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'RESOLVED'), _negated=True), fields=('kind', 'subject'), name='one_active_alert_per_problem')],
            },
        ),
    ]
