# Generated by Django 5.2.17 on 2026-09-28 20:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0002_admission_emergencyarrival_transfer_vitalreading_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('kind', models.CharField(choices=[('VENTILATOR', 'Ventilator'), ('MONITOR', 'Patient monitor'), ('INFUSION_PUMP', 'Infusion pump')], max_length=15)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('WARNING', 'Warning'), ('FAULT', 'Fault'), ('MAINTENANCE', 'In maintenance')], default='OK', max_length=12)),
                ('installed_on', models.DateField(blank=True, null=True)),
                ('last_serviced_at', models.DateTimeField(blank=True, null=True)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='hospital.bed')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='hospital.unit')),
            ],
            options={
                'verbose_name_plural': 'equipment',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature', models.FloatField(verbose_name='Internal temperature (°C)')),
                ('running_hours', models.FloatField()),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('pressure', models.FloatField(blank=True, null=True, verbose_name='Pressure (cmH₂O)')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='equipment.equipment')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['equipment', '-recorded_at'], name='equipment_e_equipme_f144e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='equipment.equipment')),
                ('finished_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('finished_at__isnull', True)), fields=('equipment',), name='one_open_maintenance_per_equipment')],
            },
        ),
    ]
