# Generated by Django 5.2.17 on 2026-09-28 19:42

import django.db.models.deletion
import hospital.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(default=hospital.models.generate_mrn, editable=False, max_length=20, unique=True, verbose_name='MRN')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('unit_type', models.CharField(choices=[('ICU', 'Intensive Care Unit'), ('WARD', 'General Ward'), ('ED', 'Emergency Department')], max_length=10)),
                ('floor', models.PositiveSmallIntegerField(default=1)),
                ('map_x', models.PositiveIntegerField(default=0)),
                ('map_y', models.PositiveIntegerField(default=0)),
                ('map_width', models.PositiveIntegerField(default=200)),
                ('map_height', models.PositiveIntegerField(default=150)),
            ],
            options={
                'ordering': ['floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('FREE', 'Free'), ('OCCUPIED', 'Occupied'), ('CLEANING', 'Cleaning')], default='FREE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('map_x', models.PositiveIntegerField(default=0)),
                ('map_y', models.PositiveIntegerField(default=0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='hospital.unit')),
            ],
            options={
                'ordering': ['unit', 'code'],
                'indexes': [models.Index(fields=['unit', 'status'], name='hospital_be_unit_id_ef2a6c_idx')],
            },
        ),
    ]
