# Generated by Django 5.2.17 on 2026-09-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_admission_emergencyarrival_transfer_vitalreading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='status_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
