# Generated by Django 5.2.17 on 2026-09-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField(default=60)),
                ('running', models.BooleanField(default=False)),
                ('anchor_sim_time', models.DateTimeField(blank=True, null=True)),
                ('anchor_real_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
