# Generated by Django 5.2.17 on 2026-10-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalclock',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
