# Generated by Django 5.2.17 on 2026-10-01 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('hospital', '0003_bed_status_since'),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectedFault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('hours_to_failure', models.FloatField()),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injected_faults', to='equipment.equipment')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientPhysiology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline', models.JSONField()),
                ('deterioration_onset_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('last_reading_at', models.DateTimeField(blank=True, null=True)),
                ('last_temperature_at', models.DateTimeField(blank=True, null=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physiology', to='hospital.admission')),
            ],
            options={
                'verbose_name_plural': 'patient physiology',
            },
        ),
    ]
